name: meeper

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Commit author'
        required: true
      repo:
        description: 'Originating repository'
        required: true
      id:
        description: 'Commit id'
        required: true
      message:
        description: 'Commit message'
        required: true

# This job is only meant to be triggered manually
jobs:
  meeper:
    runs-on: ubuntu-latest
    name: meeper
    steps:
      - name: meeper
        id: meeper
        uses: moreeyesplz/meeper@master
