name: meeper

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Commit author'
        required: true
      repo:
        description: 'Originating repository'
        required: true
      id:
        description: 'Commit id'
        required: true
      message:
        description: 'Commit message'
        required: true
      owner:
        description: 'Repo owner'
        required: true

# This job is only meant to be triggered manually
jobs:
  meeper:
    runs-on: ubuntu-latest
    name: meeper
    steps:
      - uses: moreeyesplz/meeper@master
        with:
          bot_id: ${{ secrets.BOT_ID }}
          bot_key: ${{ secrets.BOT_KEY }}
          bot_install_id: ${{ secrets.BOT_INSTALL_ID }}
